version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=voucher_selection
    hostname: postgres.host
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U user -h postgres_db -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    container_name: voucher_selection_api
    build: .
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    environment:
      - APP_DB_HOST=postgres.host
      - APP_DB_USERNAME=user
      - APP_DB_PASSWORD=password
      - APP_DB_DATABASE=voucher_selection
    networks:
      - app
    depends_on:
      - postgres_db

networks:
  app:

volumes:
  db-data: