# -*- coding: utf-8 -*-
"""data_exploration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytCjQMrCo5grWQaXMBp_4GLBsaDTDUGU
"""

import pandas as pd

df = pd.read_parquet('/content/drive/MyDrive/data.parquet.gzip')

df.head(10)

df_peru = df[df.country_code == 'Peru']

df_peru.head(10)

df_peru.info()

df_peru.count()

df_peru[df_peru.total_orders == '']

count_no_total_orders = df_peru[df_peru.total_orders == ''].shape[0]

df_peru[df_peru.voucher_amount.isna()]

count_no_voucher_amount = df_peru[df_peru.voucher_amount.isna()].shape[0]

print(f'{round(count_no_total_orders/df_peru.shape[0] * 100)}% data with no correct order count')
print(f'{round(count_no_voucher_amount/df_peru.shape[0] * 100)}% data with no voudher amount')

df_peru.voucher_amount = df_peru.voucher_amount.fillna(0)

df_peru_update_voucher_amount = df_peru.copy()
df_peru_update_voucher_amount.voucher_amount = df_peru_update_voucher_amount.voucher_amount.astype(int)

df_peru_update_voucher_amount.head(10)

df_peru_total_orders_update = df_peru_update_voucher_amount.copy()
df_peru_total_orders_update.loc[(df_peru_total_orders_update.total_orders == ''), 'total_orders'] = 0

df_peru_total_orders_update.total_orders = df_peru_total_orders_update.total_orders.astype(float).astype(int)

df_peru_total_orders_update.head(10)

df_peru_update_timestamp = df_peru_total_orders_update.copy()
df_peru_update_timestamp.timestamp = pd.to_datetime(df_peru_update_timestamp.timestamp)
df_peru_update_timestamp.last_order_ts = pd.to_datetime(df_peru_update_timestamp.last_order_ts)

df_peru_update_timestamp.info()

df_peru_update_timestamp[df_peru_update_timestamp.duplicated()]

df_peru_deduplicate = df_peru_update_timestamp.drop_duplicates(keep='first')

df_peru_deduplicate.shape

df_peru_deduplicate.head(10)